// Generated by Wrangler / Open-Next
interface CloudflareEnv {
  DB: any;
  AI?: any;
  GEMINI_API_KEY?: string;
  LLM_PROVIDER: string;
  LLM_MODEL?: string;
  NVIDIA_BASE_URL?: string;
  NVIDIA_API_KEY?: string;
}
